In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
abalone_train = pd.read_csv(
    "winequalityN.csv",
    names=["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"])
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')
abalone_labels = abalone_train.quality.apply(lambda q: 1 if q == 6 else 0)
abalone_features = np.array(abalone_features)
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
from sklearn.model_selection import GridSearchCV

In [3]:
#[('ccp_alpha', 0), ('criterion', 'gini'), ('splitter', 'random')]
parameters={'criterion':('friedman_mse','squared_error'),
            'learning_rate':(0,1,2),}

In [4]:
clf = GridSearchCV(GradientBoostingClassifier(), parameters)
import warnings
warnings.filterwarnings("ignore")
clf.fit(X_train, y_train)

GridSearchCV(estimator=GradientBoostingClassifier(),
             param_grid={'criterion': ('friedman_mse', 'squared_error'),
                         'learning_rate': (0, 1, 2)})

In [5]:
predictions = clf.predict(X_test)

In [6]:
import sklearn
sklearn.metrics.roc_curve(y_test,predictions)

(array([0., 0., 1.]), array([0., 1., 1.]), array([inf,  1.,  0.]))

In [7]:
sklearn.metrics.roc_auc_score(y_test,predictions)

1.0

In [8]:
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[4, 0],
       [0, 2]], dtype=int64)

In [9]:
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[4, 0],
       [0, 2]], dtype=int64)

In [11]:
sklearn.metrics.log_loss(y_test,predictions)

2.220446049250313e-16