In [1]:
import pandas as pd

In [2]:
abalone_train = pd.read_csv(
    "winequalityN.csv",
    names=["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"])

In [3]:
print(abalone_train.head())

   type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1            7.0              0.27         0.36            20.7   
1     1            6.3              0.30         0.34             1.6   
2     1            8.1              0.28         0.40             6.9   
3     1            7.2              0.23         0.32             8.5   
4     1            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     

In [4]:
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')

In [5]:
abalone_features

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0       1            7.0              0.27         0.36            20.7   
1       1            6.3              0.30         0.34             1.6   
2       1            8.1              0.28         0.40             6.9   
3       1            7.2              0.23         0.32             8.5   
4       1            7.2              0.23         0.32             8.5   
..    ...            ...               ...          ...             ...   
104     1            7.4              0.25         0.37            13.5   
105     1            7.3              0.13         0.32            14.4   
106     1            7.1              0.12         0.32             9.6   
107     1            7.1              0.23         0.35            16.5   
108     1            7.1              0.23         0.35            16.5   

     chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0        0.045                 45.0                 170.0   1.0010  3.00   
1        0.049                 14.0                 132.0   0.9940  3.30   
2        0.050                 30.0                  97.0   0.9951  3.26   
3        0.058                 47.0                 186.0   0.9956  3.19   
4        0.058                 47.0                 186.0   0.9956  3.19   
..         ...                  ...                   ...      ...   ...   
104      0.060                 52.0                 192.0   0.9975  3.00   
105      0.051                 34.0                 109.0   0.9974  3.20   
106      0.054                 64.0                 162.0   0.9962  3.40   
107      0.040                 60.0                 171.0   0.9990  3.16   
108      0.040                 60.0                 171.0   0.9990  3.16   

     sulphates  alcohol  
0         0.45      8.8  
1         0.49      9.5  
2         0.44     10.1  
3         0.40      9.9  
4         0.40      9.9  
..         ...      ...  
104       0.44      9.1  
105       0.35      9.2  
106       0.41      9.4  
107       0.59      9.1  
108       0.59      9.1  

[109 rows x 12 columns]

In [6]:
abalone_labels

0      6
1      6
2      6
3      6
4      6
      ..
104    5
105    6
106    5
107    6
108    6
Name: quality, Length: 109, dtype: int64

In [7]:
import numpy as np
abalone_features = np.array(abalone_features)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
logmodel = LogisticRegression(max_iter=1000,solver='saga', penalty='elasticnet', l1_ratio=0.5)
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.3333333333333333


C:\Users\OZadorozhnyi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [11]:
abalone_train.value_counts()

type  fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  density  pH    sulphates  alcohol  quality
1     7.1            0.120             0.32         9.6             0.054      64.0                 162.0                 0.9962   3.40  0.41       9.4      5          2
                     0.230             0.35         16.5            0.040      60.0                 171.0                 0.9990   3.16  0.59       9.1      6          2
      6.6            0.380             0.15         4.6             0.044      25.0                 78.0                  0.9931   3.11  0.38       10.2     6          2
      7.4            0.240             0.29         10.1            0.050      21.0                 105.0                 0.9962   3.13  0.35       9.5      5          2
                     0.250             0.37         13.5            0.060      52.0                 192.0                 0.9975   3.00  0.44       9.1    

In [13]:
import sklearn
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[0, 3, 1],
       [0, 2, 0],
       [0, 0, 0]], dtype=int64)

In [15]:
sklearn.metrics.f1_score(y_test,predictions,average=None)

array([0.        , 0.57142857, 0.        ])

In [16]:
sklearn.metrics.roc_curve(y_test,predictions)

ValueError: y_true takes value in {5, 6} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In [22]:
abalone_train.quality.apply(lambda q: 1 if q == 6 else 0)

0      1
1      1
2      1
3      1
4      1
      ..
104    0
105    1
106    0
107    1
108    1
Name: quality, Length: 109, dtype: int64

In [24]:
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')
abalone_features = np.array(abalone_features)
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)
logmodel = LogisticRegression(max_iter=1000,solver='saga', penalty='elasticnet', l1_ratio=0.5)
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
sklearn.metrics.roc_curve(y_test,predictions)

C:\Users\OZadorozhnyi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


ValueError: y_true takes value in {5, 6} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In [26]:
y_test

84     5
10     5
75     5
2      6
24     6
100    5
Name: quality, dtype: int64

In [27]:
abalone_train = abalone_train.quality.apply(lambda q: 1 if q == 6 else 0)

In [28]:
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')
abalone_features = np.array(abalone_features)
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)
logmodel = LogisticRegression(max_iter=1000,solver='saga', penalty='elasticnet', l1_ratio=0.5)
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
sklearn.metrics.roc_curve(y_test,predictions)

KeyError: 'quality'

In [29]:
abalone_features

0      1
1      1
2      1
3      1
4      1
      ..
104    0
105    1
106    0
107    1
108    1
Name: quality, Length: 109, dtype: int64

In [30]:
abalone_train

0      1
1      1
2      1
3      1
4      1
      ..
104    0
105    1
106    0
107    1
108    1
Name: quality, Length: 109, dtype: int64

In [31]:
abalone_train = pd.read_csv(
    "winequalityN.csv",
    names=["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"])


In [33]:
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')
abalone_labels = abalone_train.quality.apply(lambda q: 1 if q == 6 else 0)
abalone_features = np.array(abalone_features)
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)
logmodel = LogisticRegression(max_iter=1000,solver='saga', penalty='elasticnet', l1_ratio=0.5)
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
sklearn.metrics.roc_curve(y_test,predictions)

C:\Users\OZadorozhnyi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


(array([0.  , 0.75, 1.  ]), array([0. , 0.5, 1. ]), array([inf,  1.,  0.]))

In [35]:
sklearn.metrics.roc_auc_score(y_test,predictions)

0.375

In [36]:
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[1, 3],
       [1, 1]], dtype=int64)

In [ ]:
sklearn.metrics.confusion_matrix(y_test,predictions)

In [37]:
sklearn.metrics.log_loss(y_test,predictions)

24.029102259411435