In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
abalone_train = pd.read_csv(
    "winequalityN.csv",
    names=["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"])
abalone_features = abalone_train.copy()
abalone_features.fillna(0, inplace=True)
abalone_labels = abalone_features.pop('quality')
abalone_labels = abalone_train.quality.apply(lambda q: 1 if q == 6 else 0)
abalone_features = np.array(abalone_features)
X_train, X_test, y_train, y_test = train_test_split(
    abalone_features, abalone_labels, test_size=0.05, random_state=0)
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
from sklearn.svm import SVC

In [6]:
from sklearn.model_selection import GridSearchCV

In [7]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

In [9]:
clf = GridSearchCV(SVC(), parameters)
clf.fit(X_train, y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})

In [11]:
predictions = clf.predict(X_test)

In [14]:
import sklearn
sklearn.metrics.roc_curve(y_test,predictions)

(array([0.  , 0.75, 1.  ]), array([0., 1., 1.]), array([inf,  1.,  0.]))

In [15]:
sklearn.metrics.roc_auc_score(y_test,predictions)

0.625

In [16]:
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[1, 3],
       [0, 2]], dtype=int64)

In [17]:
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[1, 3],
       [0, 2]], dtype=int64)

In [18]:
sklearn.metrics.log_loss(y_test,predictions)

18.021826694558577